2025-04-06 17:07:15,521 - ERROR - Internal Server Error: /log_in/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\drink\main\views.py", line 118, in log_in
    return render(request,'auth/login.html',{'next':next})
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\defaulttags.py", line 1421, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '‘social:begin’' from '‘social:begin’'
2025-04-06 17:07:15,528 - ERROR - "GET /log_in/?next=/ HTTP/1.1" 500 169416
2025-04-06 22:22:18,281 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\drink\main\views.py", line 76, in index
    return render(request,"main/index.html",context,{'date':datetime.now()})
                                            ^^^^^^^
NameError: name 'context' is not defined. Did you mean: 'contact'?
2025-04-06 22:22:18,291 - ERROR - "GET / HTTP/1.1" 500 75754
2025-04-06 22:22:24,173 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\drink\main\views.py", line 76, in index
    return render(request,"main/index.html",context,{'date':datetime.now()})
                                            ^^^^^^^
NameError: name 'context' is not defined. Did you mean: 'contact'?
2025-04-06 22:22:24,177 - ERROR - "GET / HTTP/1.1" 500 75882
2025-04-07 19:12:09,990 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\drink\main\views.py", line 191, in index
    return render(request, 'main/index.html', context)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' with arguments '(1,)' not found. 1 pattern(s) tried: ['\\Z']
2025-04-07 19:12:09,998 - ERROR - "GET / HTTP/1.1" 500 184442
2025-04-07 19:12:45,056 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\drink\main\views.py", line 192, in index
    return render(request, 'main/index.html', context)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' with arguments '(1,)' not found. 1 pattern(s) tried: ['\\Z']
2025-04-07 19:12:45,071 - ERROR - "GET / HTTP/1.1" 500 184203
2025-04-07 19:14:10,471 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\drink\main\views.py", line 192, in index
    return render(request, 'main/index.html', context)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'drink_by_category' not found. 'drink_by_category' is not a valid view function or pattern name.
2025-04-07 19:14:10,476 - ERROR - "GET / HTTP/1.1" 500 183201
2025-04-07 19:35:18,119 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\drink\main\views.py", line 192, in index
    return render(request, 'main/index.html', context)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 563, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 327: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
2025-04-07 19:35:18,138 - ERROR - "GET / HTTP/1.1" 500 212458
2025-04-08 11:05:35,842 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset.html
2025-04-08 11:05:35,851 - ERROR - "GET /password_reset/ HTTP/1.1" 500 84659
2025-04-08 11:05:44,755 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset.html
2025-04-08 11:05:44,760 - ERROR - "GET /password_reset/ HTTP/1.1" 500 84924
2025-04-08 11:05:48,493 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset.html
2025-04-08 11:05:48,499 - ERROR - "GET /password_reset/ HTTP/1.1" 500 84924
2025-04-08 11:05:48,669 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset.html
2025-04-08 11:05:48,672 - ERROR - "GET /password_reset/ HTTP/1.1" 500 84924
2025-04-08 11:05:48,875 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset.html
2025-04-08 11:05:48,877 - ERROR - "GET /password_reset/ HTTP/1.1" 500 84924
2025-04-08 11:05:49,048 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset.html
2025-04-08 11:05:49,052 - ERROR - "GET /password_reset/ HTTP/1.1" 500 84924
2025-04-08 11:05:49,258 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset.html
2025-04-08 11:05:49,260 - ERROR - "GET /password_reset/ HTTP/1.1" 500 84924
2025-04-08 11:05:49,463 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset.html
2025-04-08 11:05:49,465 - ERROR - "GET /password_reset/ HTTP/1.1" 500 84924
2025-04-08 11:05:49,696 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset.html
2025-04-08 11:05:49,699 - ERROR - "GET /password_reset/ HTTP/1.1" 500 84924
2025-04-08 11:08:21,754 - ERROR - Internal Server Error: /password_reset_done/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_done.html
2025-04-08 11:08:21,760 - ERROR - "GET /password_reset_done/ HTTP/1.1" 500 85091
2025-04-08 11:26:38,934 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset
2025-04-08 11:26:38,938 - ERROR - "GET /password_reset/ HTTP/1.1" 500 85144
2025-04-08 11:26:42,747 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset
2025-04-08 11:26:42,755 - ERROR - "GET /password_reset/ HTTP/1.1" 500 85144
2025-04-08 11:26:57,795 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'static'. Did you forget to register or load this tag?
2025-04-08 11:26:57,801 - ERROR - "GET /password_reset/ HTTP/1.1" 500 141713
2025-04-08 11:27:12,175 - ERROR - Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'static'. Did you forget to register or load this tag?
2025-04-08 11:27:12,179 - ERROR - "GET /password_reset/ HTTP/1.1" 500 141713
2025-04-08 12:10:40,465 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:10:40,470 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:34,010 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:34,012 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:35,213 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:35,215 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:35,382 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:35,384 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:35,567 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:35,569 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:35,736 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:35,738 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:35,893 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:35,896 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:36,039 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:36,040 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:36,198 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:36,200 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:36,358 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:36,360 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:36,544 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:36,545 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:11:36,746 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:11:36,748 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:12:31,384 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:12:31,388 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 84954
2025-04-08 12:14:11,100 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:11,104 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 84954
2025-04-08 12:14:14,666 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:14,670 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:14:15,770 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:15,773 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:14:15,942 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:15,945 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:14:16,095 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:16,098 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:14:16,257 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:16,260 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:14:16,423 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:16,426 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:14:16,607 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:16,610 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:14:16,773 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:16,776 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:14:16,963 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:16,975 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
2025-04-08 12:14:17,100 - ERROR - Internal Server Error: /password_reset_complete/
Traceback (most recent call last):
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Asus\OneDrive\Desktop\drinker_project\myenv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: auth/password_reset_complete
2025-04-08 12:14:17,102 - ERROR - "GET /password_reset_complete/ HTTP/1.1" 500 85219
